# Uncomment this line to define a global platform for your project
# platform :ios, “7.0”

#target “ZYZone” do

platform :ios, '7.0'

pod 'FlurrySDK', '~> 5.3'
pod 'CrashlyticsFramework', '~> 2.2'
pod 'AFNetworking', '~> 2.3'
pod 'FXImageView', '~> 1.3'
pod 'MBProgressHUD', '~> 0.9'
pod 'HMSegmentedControl', '~> 1.4'
pod 'SDWebImage', '~> 3.7'
pod 'MagicalRecord', '~> 2.2'

#end

#target "ZYZoneTests" do

#end

